export const TOGGLE_DISPLAY_MODE = 'TOGGLE_DISPLAY_MODE';
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
export const UPDATE_TORRENTS = 'UPDATE_TORRENTS';
export const TOGGLE_TORRENT_SELECTION = 'TOGGLE_TORRENT_SELECTION';
export const TOGGLE_OPEN_DIALOG = 'TOGGLE_OPEN_DIALOG';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_FOCUS_CHANGE = 'SEARCH_FOCUS_CHANGE';
